operator:
  sloChecker:
    droppedRecordsKStreams:
      enabled: false
  resultsVolume:
    enabled: false

strimzi:
  kafka:
    replicas: 1
    config:
      "offsets.topic.replication.factor": "1"
    resources:
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "1"
